@startuml
class Exception << General >>

package "pt.isel.ls" #DDDDDD {
    class App

    package "exceptions" #DDDDDD {
    }
    package "handlers" #DDDDDD {

        package "handlers.activities" #DDDDDD {
            class CreateActivityHandler
            class DeleteActivitiesByUidAidHandler
            class GetActivitiesBySidHandler
            class GetActivitiesByTopsHandler
            class GetActivitiesByUidHandler
            class GetActivityByAidSidHandler
        }

        package "handlers.routes" #DDDDDD {
            class CreateRouteHandler
            class GetAllRoutesHandler
            class GetRouteByIdHandler
        }

        package "handlers.sports" #DDDDDD {
            class CreateSportHandler
            class GetAllSportsHandler
            class GetSportByIdHandler
        }

        package "handlers.users" #DDDDDD {
            class CreateUserHandler
            class GetAllUsersHandler
            class GetUserByIdHandler
        }
    }

    package "models" #DDDDDD {
        package "models.domainclasses" #DDDDDD {
            class Activity
            class Route
            class Sport
            class User
        }

        class ActivitiesModel
        class RoutesModel
        class SportsModel
        class UserModel
    }

    package "request" #DDDDDD {
        enum Method
        class Request
        interface RequestHandler
    }

    package "results" #DDDDDD {
        package "results.activities" #DDDDDD {
            class CreateActivityResult
            class DeleteActivitiesByUidAidResult
            class GetActivitiesBySidResult
            class GetActivitiesByTopsResult
            class GetActivitiesByUidResult
            class GetActivityByAidSidResult
        }
        package "results.routes" #DDDDDD {
            class CreateRouteResult
            class GetAllRoutesResult
            class GetRouteByIdResult
        }

        package "results.sports" #DDDDDD {
            class CreateSportResult
            class GetAllSportsResult
            class GetSportByIdResult
        }
        package "results.users" #DDDDDD {
            class CreateUserResult
            class GetAllUsersResult
            class GetUserByIdResult
        }

        class OptionResult
        abstract RequestResult
    }

    package "routers" #DDDDDD {
        class HandlerRouter
        class Node
        class ViewRouter
    }

    package "utils" #DDDDDD {
        class utils
    }

    package "views" #DDDDDD {
        package "views.activities" #DDDDDD {
            package "views.activities.html" #DDDDDD {
                class CreateActivityHtml
                class DeleteActivitiesByUidAidHtml
                class GetActivitiesBySidHtml
                class GetActivitiesByTopsHtml
                class GetActivitiesByUidHtml
                class GetActivityByAidSidHtml
            }
            package "views.activities.json" #DDDDDD {
                class CreateActivityJson
                class DeleteActivitiesByUidAidJson
                class GetActivitiesBySidJson
                class GetActivitiesByTopsJson
                class GetActivitiesByUidJson
                class GetActivityByAidSidJson
            }
            package "views.activities.plaintext" #DDDDDD {
                class CreateActivityPlainText
                class DeleteActivitiesByUidAidPlainText
                class GetActivitiesBySidResultPlainText
                class GetActivitiesByTopsPlainText
                class GetActivitiesByUidResultPlainText
                class GetActivityByAidSidResultPlainText
            }
        }

        package "views.builders" #DDDDDD {
                package "views.builders.html" #DDDDDD {
                    package "views.builders.html.parts" #DDDDDD {
                        class Body
                        class DD
                        class DL
                        class DT
                        class H1
                        class Head
                        class Html
                        class LI
                        class Table
                        class TD
                        class TH
                        class Title
                        class TR
                        class UL
                    }
                    abstract Element
                    class HtmlBuilder
                    class HtmlGetter
                }
                package "views.builders.json" #DDDDDD {
                    package "views.builders.json.parts" #DDDDDD {
                        class JsonArray
                        class JsonKey
                        class JsonObject
                        class JsonPut
                        class JsonValue
                    }
                    class JsonBuilder
                    abstract JsonElement
                    class JsonGetter
                }
                package "views.builders.plaintext" #DDDDDD {
                    class PlainTextGetter
                }
        }

        package "views.routes" #DDDDDD {
                package "views.routes.html" #DDDDDD {
                    class CreateRouteHtml
                    class GetAllRoutesHtml
                    class GetRouteByIdHtml
                }
                package "views.routes.json" #DDDDDD {
                    class CreateRouteJson
                    class GetAllRoutesJson
                    class GetRouteByIdJson
                }
                package "views.routes.plaintext" #DDDDDD {
                    class CreateRoutePlainText
                    class GetAllRoutesPlainText
                    class GetRouteByIdPlainText
                }

        }

        package "views.sports" #DDDDDD {
                package "views.sports.html" #DDDDDD {
                    class CreateSportHtml
                    class GetAllSportsHtml
                    class GetSportByIdHtml
                }
                package "views.sports.json" #DDDDDD {
                    class CreateSportJson
                    class GetAllSportsJson
                    class GetSportByIdJson
                }
                package "views.sports.plaintext" #DDDDDD {
                    class CreateSportPlainText
                    class GetAllSportsPlainText
                    class GetSportByIdPlainText
                }
        }

        package "views.users" #DDDDDD {
                package "views.users.html" #DDDDDD {
                    class CreateUserHtml
                    class GetAllUsersHtml
                    class GetUserByIdHtml
                }
                package "views.users.json" #DDDDDD {
                    class CreateUserJson
                    class GetAllUsersJson
                    class GetUserByIdJson
                }
                package "views.users.plaintext" #DDDDDD {
                    class CreateUserPlainText
                    class GetAllUsersPlainText
                    class GetUserByIdPlainText
                }
        }

        class OptionPlainText
        Interface View
    }
}
@enduml